# Generated by Django 4.2.3 on 2023-07-28 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('maths', models.DecimalField(decimal_places=2, max_digits=5)),
                ('chemistry', models.DecimalField(decimal_places=2, max_digits=5)),
                ('physics', models.DecimalField(decimal_places=2, max_digits=5)),
                ('history', models.DecimalField(decimal_places=2, max_digits=5)),
                ('literature', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
